name: Update README
on:
  schedule:
    - cron: "*/10 * * * *"
    # - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: jarooda/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: "jarooda"
          COMMIT_NAME: GitHub Activity Readme
          COMMIT_MSG: "chore: update README with the recent activity"
          EMPTY_COMMIT_MSG: "chore: update README with the recent activity"